# build.yml

name: Build

on:
  workflow_dispatch:
    inputs:
      mfem-ref:
        type: string
        default: 'master'
      glvis-ref:
        type: string
        default: 'master'
      emscripten-version:
        type: string
        default: '3.1.51'

jobs:
  build:
    runs-on: ubuntu-latest

    name: >-
        build glvis-js |
        mfem=${{ inputs.mfem-ref }} | 
        glvis=${{ inputs.glvis-ref }} | 
        emcc=${{ inputs.emscripten-version }}

    steps:
    # ---------------------------------------------------------------------------------
    # Install glvis-js and dependencies
    # ---------------------------------------------------------------------------------
    - name: Checkout glvis-js
      uses: actions/checkout@v4
      with:
        submodules: recursive
        path: glvis-js

    - name: Install glvis dependencies
      run: |
        sudo apt-get install libfontconfig1-dev libfreetype-dev libsdl2-dev \
        libglew-dev libglm-dev libpng-dev

    - name: Checkout emscripten
      uses: actions/checkout@v4
      with:
        repository: emscripten-core/emsdk
        path: emsdk

    - name: Install emscripten
      run: |
        cd emsdk
        ./emsdk install ${{ inputs.emscripten-version }}
        ./emsdk activate ${{ inputs.emscripten-version }}
        echo "${GITHUB_WORKSPACE}/emsdk" >> $GITHUB_PATH
        echo "${GITHUB_WORKSPACE}/emsdk/upstream/emscripten" >> $GITHUB_PATH

    - name: Checkout mfem
      uses: actions/checkout@v4
      with:
        repository: mfem/mfem
        ref: ${{ inputs.mfem-ref }}
        path: mfem

    - name: Checkout glvis
      uses: actions/checkout@v4
      with:
        repository: glvis/glvis
        ref: ${{ inputs.glvis-ref }}
        path: glvis

    - name: Install glvis-js (also installs mfem + glvis)
      run: | 
        cd glvis-js
        make install -j 4

    # ---------------------------------------------------------------------------------
    # Generate an artifact
    # ---------------------------------------------------------------------------------
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
          name: glvis-js
          path: glvis-js/src
          retention-days: 1
